#ifndef DCAPP_BUILD_CONTRACT_H
#define DCAPP_BUILD_CONTRACT_H

/* Generated by tools/gen_dcapp_build_contract.py. */
#define DCAPP_BUILD_CONTRACT_SCHEMA 1u
#define DCAPP_BUILD_CONTRACT_HEX "6192dd44894acd573da2f0514f5f8a13866c1b748d7c5f1941fb494ca0fc75cc"
#define DCAPP_BUILD_CONTRACT_WORDS 0x44dd9261u, 0x57cd4a89u, 0x51f0a23du, 0x138a5f4fu

#endif
