#!/usr/bin/env python3
"""Generate a linker-script import table for fixed-address DCAPP modules."""

from __future__ import annotations

import argparse
import re
import subprocess
from pathlib import Path


SYMBOL_RE = re.compile(r"^([0-9a-fA-F]+)\s+([A-Za-z])\s+(.+)$")
EXPORTED_TYPES = set("ABCDGIRSTVW")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--nm", required=True, type=Path)
    parser.add_argument("--elf", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    proc = subprocess.run(
        [str(args.nm), "-g", "--defined-only", str(args.elf)],
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        check=True,
    )
    exports: dict[str, int] = {}
    for line in proc.stdout.splitlines():
        match = SYMBOL_RE.match(line.strip())
        if not match:
            continue
        addr_s, sym_type, name = match.groups()
        if sym_type.upper() not in EXPORTED_TYPES:
            continue
        if name.startswith("$") or "." in name:
            continue
        exports[name] = int(addr_s, 16)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", encoding="ascii", newline="\n") as out:
        out.write("/* Generated by tools/gen_dcapp_host_symbols.py */\n")
        for name in sorted(exports):
            out.write(f"PROVIDE({name} = 0x{exports[name]:08x});\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
