#!/usr/bin/env python3
"""Generate fixed-address Thumb veneers for the DCAPP SDK v1 import surface."""

from __future__ import annotations

import argparse
from pathlib import Path


# This is intentionally a curated ABI, not the firmware's complete symbol table.
# Adding or changing an entry is an SDK ABI change and requires a version bump.
IMPORTS = """
accessFail arduboyAnalyzeRom arduboyClearFxCache arduboyExtractPackageToFlash
arduboyPortInGameMenu audioPwmGetVolume audioPwmSetMasterVolume audioPwmSetVolume
audioPwmStop audioPwmTone badgeLedsApplySettings badgeLedsColorName badgeLedsGameWrite
badgeLedsModeName badgeLedsOverrideRgb badgeLedsTick badgePowerGetCached badgePowerPoll
badgePowerReadNow badgeRtcDaysInMonth badgeRtcGet badgeRtcGetDateTime badgeRtcGetTimeOfDay
badgeRtcIsValid badgeRtcReadHardware badgeRtcSetDateTime bootGuardClear bootGuardEnter
bootGuardExit bootGuardRecoveredCrashInfo bootGuardRecoveredMode dcAppCatalogEntries
dcAppClearError dcAppDrawClear dcAppDrawFill dcAppDrawFrame dcAppDrawInit dcAppDrawLine
dcAppDrawLoading dcAppDrawLoadingCanvas dcAppDrawPixel dcAppDrawPresent dcAppDrawRgb565
dcAppDrawSetThemeColor dcAppDrawWaitRelease dcAppGetActiveScratch dcAppLastError
dcAppResultName dcAppRunTool delayUsec dispGetFb dispInit dispOff dispPauseScanout
dispPrvFrameCtrReset dispPrvFrameCtrWait dispPrvWaitForScanoutStart dispResumeScanout
dispSetBrightness dispSetContrast dispSetFramerate doSleep fatfsClearLastCreateError
fatfsDirClose fatfsDirCreate fatfsDirCreateAt fatfsDirDeleteAt fatfsDirOpen fatfsDirOpenAt
fatfsDirOpenWithLocator fatfsDirRead fatfsFileClose fatfsFileCreateAt fatfsFileDelete
fatfsFileDeleteAt fatfsFileGetSize fatfsFileOpen fatfsFileOpenAt fatfsFileOpenWithLocator
fatfsFileRead fatfsFileSeek fatfsFileTell fatfsFileTruncate fatfsFileWrite fatfsFindFileAt
fatfsLastCreateError fatfsLastCreateErrorName fatfsMount fatfsUnmount flashGetUid flashWrite
flashUncachedPtr fontGetGlyphInfo fontGetGlyphPixel fontGetHeight gbDrawLine gbExtAccelRead
gbExtGetKeys gbExtRtcGet gbExtRtcReset gbExtRtcSet gbExtraIoRegRead gbExtraIoRegWrite getTime
imageViewerAlloc imageViewerCalloc imageViewerFileName imageViewerFree imageViewerGifClose
imageViewerGifOpen imageViewerGifRead imageViewerGifSeek imageViewerRealloc imageViewerRun
imageViewerRunStill irRemoteRxControl irdaSIRuartConfig mbcRomAnalyze nesAnalyzeRom
nesPortInGameMenu panic sdCardInit sdClearLastError sdGetFlags sdGetLastError sdGetNumSecs
sdReadNext sdReadStart sdReadStop sdReportLastError sdSecRead sdSecWrite sdSetSpeedLimit
sdWriteNext sdWriteStart sdWriteStop settingsGet settingsSet timebaseIdleWaitMsec
toolWorkspaceAcquire toolWorkspaceBegin toolWorkspaceEnd toolWorkspaceGet toolWorkspaceRelease
uiGetKeysRaw uiGetUiKeys uiGetUiKeysRaw uiPowerApplySettings uiPowerConsumeScreenSaverWake
uiPowerScreenSaverWoke uiPowerSetActiveBrightness uiPowerSetIdleInhibited
uiPowerSetScreenSaverContentActive uiReadTouchRaw usbCdcAvailable usbCdcBegin usbCdcConnected
usbCdcDefaultInfo usbCdcEnd usbCdcFlush usbCdcRead usbCdcTask usbCdcWrite
usbCdcWriteAvailable usbHidBegin usbHidBeginReportSet usbHidConsumerReport usbHidDefaultInfo
usbHidDropNow usbHidEnd usbHidGamepadFeedback usbHidGamepadReport usbHidGamepadReportTouch
usbHidKeyboardReport usbHidLastError usbHidMouseReport usbHidReady usbHidReleaseAll
usbHidSetReportsEnabled usbHidTask usbMscBegin usbMscEjected usbMscEnd usbMscGetStatus
usbMscLastError usbMscMounted usbMscTask usbMscWritable usbXinputBegin usbXinputEnd
usbXinputFeedback usbXinputLastError usbXinputReady usbXinputReleaseAll usbXinputReport
usbXinputSetReportsEnabled usbXinputTask utf8inputByte utf8stateStart utfToCaseless vxprintf
ws2812SetRgb ws2812refresh
""".split()


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()
    lines = ["/* Generated by tools/gen_dcapp_abi_veneers.py. */", ".syntax unified", ".thumb",
             ".section .dcapp_abi_veneer, \"ax\", %progbits", ".align 2"]
    for name in IMPORTS:
        veneer = f"dcapp_abi_veneer_{name}"
        lines += [f".global {veneer}", f".type {veneer}, %function", f".thumb_func", f"{veneer}:",
                  "  ldr.w r12, [pc, #4]", "  bx r12", "  .align 2", f"  .word {name} + 1"]
    body = "\n".join(lines) + "\n"
    args.output.parent.mkdir(parents=True, exist_ok=True)
    if not args.output.exists() or args.output.read_text(encoding="ascii") != body:
        args.output.write_text(body, encoding="ascii", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
