#!/usr/bin/env python3
"""Generate the firmware/app build contract used by DCAPP launch checks."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("inputs", nargs="*", type=Path)
    return parser.parse_args()


def file_digest(root: Path, inputs: list[Path]) -> bytes:
    h = hashlib.sha256()
    for raw_path in sorted({path.resolve() for path in inputs}):
        if not raw_path.is_file():
            continue
        rel = raw_path.relative_to(root).as_posix() if raw_path.is_relative_to(root) else raw_path.as_posix()
        data = raw_path.read_bytes()
        h.update(rel.encode("utf-8"))
        h.update(b"\0")
        h.update(len(data).to_bytes(8, "little"))
        h.update(data)
        h.update(b"\0")
    return h.digest()


def main() -> int:
    args = parse_args()
    root = args.root.resolve()
    digest = file_digest(root, args.inputs)
    words = [int.from_bytes(digest[i : i + 4], "little") for i in range(0, 16, 4)]
    body = (
        "#ifndef DCAPP_BUILD_CONTRACT_H\n"
        "#define DCAPP_BUILD_CONTRACT_H\n"
        "\n"
        "/* Generated by tools/gen_dcapp_build_contract.py. */\n"
        "#define DCAPP_BUILD_CONTRACT_SCHEMA 1u\n"
        f"#define DCAPP_BUILD_CONTRACT_HEX \"{digest.hex()}\"\n"
        "#define DCAPP_BUILD_CONTRACT_WORDS "
        + ", ".join(f"0x{word:08x}u" for word in words)
        + "\n"
        "\n"
        "#endif\n"
    )

    args.output.parent.mkdir(parents=True, exist_ok=True)
    if args.output.exists() and args.output.read_text(encoding="ascii") == body:
        return 0
    args.output.write_text(body, encoding="ascii", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
