#ifndef _TUSB_CONFIG_H_
#define _TUSB_CONFIG_H_

#define CFG_TUSB_MCU OPT_MCU_RP2040
#define CFG_TUSB_OS OPT_OS_NONE
#define CFG_TUSB_DEBUG 0

#define CFG_TUSB_RHPORT0_MODE (OPT_MODE_DEVICE | OPT_MODE_FULL_SPEED)
#define CFG_TUD_ENABLED 1
#define CFG_TUD_MAX_SPEED OPT_MODE_FULL_SPEED

#define CFG_TUSB_MEM_SECTION
#define CFG_TUSB_MEM_ALIGN __attribute__((aligned(4)))

#define CFG_TUD_ENDPOINT0_SIZE 64
#define CFG_TUD_HID 1
#define CFG_TUD_CDC 1
#define CFG_TUD_MSC 1
#define CFG_TUD_MIDI 0
#define CFG_TUD_VENDOR 4

#define CFG_TUD_HID_EP_BUFSIZE 64
#define CFG_TUD_CDC_NOTIFY 1
#define CFG_TUD_CDC_RX_BUFSIZE 4096
#define CFG_TUD_CDC_TX_BUFSIZE 512
#define CFG_TUD_CDC_EP_BUFSIZE 64
#define CFG_TUD_VENDOR_EPSIZE 32
#define CFG_TUD_VENDOR_RX_BUFSIZE 0
#define CFG_TUD_VENDOR_TX_BUFSIZE 32
#define CFG_TUD_MSC_EP_BUFSIZE 2048

#define TUD_OPT_RP2040_USB_DEVICE_ENUMERATION_FIX 0
#define TUD_OPT_RP2040_USB_DEVICE_UFRAME_FIX 0
#define CFG_TUD_RPI_PIO_USB 0

#ifndef __not_in_flash
#define __not_in_flash(group)
#endif

#endif
